CREATE TABLE flats
(
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    remote_id  INT UNSIGNED,
    `type`     TINYINT UNSIGNED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_remote_id ON flats (remote_id);
